apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: axion
  labels:
    app: postgres

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:16

          ports:
            - name: postgres
              containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: "axion_user"

            - name: POSTGRES_PASSWORD
              value: "Admin@1234"

            - name: POSTGRES_DB
              value: "axion_db"